### ISSUE TITLE
How to - Install with systemjs

### ISSUE THREAD

**Issue by natcohen** [nol13/fuzzball.js#1]
I would like to install fuzzball in angular 2 using systemjs (not require) how can I do?

**Comment by nol13** [comment]
Hmm, well for one thing just realized I hadn't included /lib in the package.json after a recent refactor, which certainly would have caused some issues. Have just updated the package to fix that.

Have not used those exactly, but guessing would need to run through either systemjs-builder or jspm. 

Not sure about your exact workflow, and havent really used jspm much, but something along these lines seemed to work..

in app/main.js..

```js
var fuzz = require('fuzzball');
alert(fuzz.ratio('fuzz', 'fuzzy'));
```

in test.html..

```
<!doctype html>
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script src="build.js"></script>
<script>
    System.import('app/main.js');
</script>
```

then to build..

```
sudo npm install jspm -g
jspm init
jspm install npm:fuzzball
jspm bundle app/main build.js
```

Can take a look again when I get a chance probably later this week. Would certainly like to make it easy to use with most of the common formats.

**Comment by nol13** [comment]
So looks like making the main entry point for this a pre-bundled UMD style file might be the way to go..
 which you could then use with SystemJS like below without any additional build steps. Not merged into master yet but have just pushed a 'umd' branch with these changes. This more or less how you'd be using? Also out of curiosity are you using TypeScript with Angular 2? Probably will add some type defs eventually.

```
<!doctype html>
<script src="system.js"></script>
<script>
    System.import('fuzzball.umd.min.js').then(function(fuzz){
        alert(fuzz.ratio('fuzz', 'fuzzy'));
    });
</script>
```

**Comment by natcohen** [comment]
Yes, the umd file is what I use with the other libraries! And yes, I'm using Angular 2 with typescript... I will try as soon as you release it on the main branch!

**Comment by nol13** [comment]
main branch now officially umd

**Comment by natcohen** [comment]
Works great! However, in some cases I don't get the expected results... you should really add a demo page so we can test online. It will really help to track bugs!

**Comment by nol13** [comment]
hmm, example? Not full demo but there is a "try on runkit" button at the top of the readme.

**Comment by nol13** [comment]
fwiw if using, making that the main potentially causes issues with other build systems, so the bundled umd file now in /dist

**Comment by natcohen** [comment]
I'm sometimes surprised by the results... if you provide a test page where we can define the options and and test our strings we could see if there is a bug.

**Comment by nol13** [comment]
Right on, not 100% sure when I'd have a chance to get to it but might try something along those lines.
