### ISSUE TITLE
Won't be able to use fuzzball in my svelte project

### ISSUE THREAD

**Issue by soukand** [nol13/fuzzball.js#22]
Hello!
When building the svelte project source code, i'm getting the following error:
<img width="1111" alt="Screenshot 2021-11-19 at 20 07 58" src="https://user-images.githubusercontent.com/10027416/142685726-018d5c58-2036-473f-ab2a-6c9416793623.png">

**Comment by soukand** [comment]
Also created the PR to fix this issue 
https://github.com/nol13/fuzzball.js/pull/21

**Comment by nol13** [comment]
Thanks!

Still not super clear to me if this is an isues with svelte, or if node will be updating the api for this (https://github.com/nodejs/node/issues/33460), but ya guess not an issue to add it ¯\\_(ツ)_/¯  Published in v2.0.4

**Comment by soukand** [comment]
Thank you very much for responding quickly.
Your library helps me a lot.
