### ISSUE TITLE
Idea: AbortController support

### ISSUE THREAD

**Issue by soukand** [nol13/fuzzball.js#25]
It is pretty rare that someone has implemented cancellation in a javascript project. 
This is awesome.
In javascript, there is a standard way how to implement cancellation now.
It is called abort controller https://developer.mozilla.org/en-US/docs/Web/API/AbortController
It was shipped with node 15 and is in the current LTS version. All modern browsers are supporting it as well.
What do you think about it?
I can help you with creating the PR.

**Comment by nol13** [comment]
I'd be open to a standards compliant way to do this.

Main concerns would be backwards compatibility and node14 support. Maybe it could support both this and the existing behavior until node 14 is EOL though?

**Comment by soukand** [comment]
I think there doesn't have to be AbortController support present. 
We can just need to have one attribute present.
 
```js
const abortController = new AbortController();

setTimeout(() => abortController.abort(), Math.random() * 4000);
setTimeout(() => {
    if (abortController.signal.aborted) {
        return console.log('aborted')
    }

    console.log('not aborted');
}, 2000);
```
https://github.com/nol13/fuzzball.js/blob/dbedfa6237395b313513c2f14b626cf637075818/lite/fuzzball_lite.js#L431

So checking `abortController.signal.aborted` attribute does the trick.

**Comment by nol13** [comment]
`const abortController = new AbortController();`

to run this line you would need support though right? or you would just pass in a simulated 'signal' object as an option?

 like..?  {..., signal: {aborted: false}}

**Comment by soukand** [comment]
I will try to create a PR today and show you what I mean.

**Comment by soukand** [comment]
Here is the PR. Happy to get some feedback what can i do to improve it.
https://github.com/nol13/fuzzball.js/pull/26

**Comment by nol13** [comment]
Cool, ya I think that works. Just meant, if someone is on node 14 they wont be able to call "new AbortController()" exactly, but as long as they still have a way to do it and existing code won't break, looks good!

Really only thing I'm not 100% sure about is exactly how to mention it in the docs. Like if cancelToken should be marked as deprecated yet and such, but I can mull it over. We finally just upgraded to v12 I think ;)

**Comment by soukand** [comment]
Improved the documentation in my PR

**Comment by nol13** [comment]
v2.1.0 released!

**Comment by soukand** [comment]
Thanks again @nol13 !
