### ISSUE TITLE
Any plans to add Smith-Waterman algorithm?

### ISSUE THREAD

**Issue by vipetrul** [nol13/fuzzball.js#47]
Any plans to add Smith-Waterman algorithm?
Or perhaps the same outcome can be achieved using existing functionality?
Than you

**Comment by nol13** [comment]
I don't, but possibly something I could look into.

If you have an existing implementation of this algorithm, you could use it as a custom scorer within fuzzball to still be able to utilize the fuzzball utilities though. A quick search turned up a few packages on github that might work for this, but I have not tried them myself.

**Comment by vipetrul** [comment]
Thanks for looking into this. I did try one the the existing implementations, unfortunately performance on larger strings didn't meet my needs.
