### ISSUE TITLE
More permissive licences?

### ISSUE THREAD

**Issue by dimaip** [nol13/fuzzball.js#58]
Hi!
Is GPL used for this project deliberately?

We were banned from using this lib in our project by our legal team because apparently installing a package is not considered "Separate Works".
If you could reconsider a more permissive licence that would actually allow usage in a commercial project, that would be amazing!

**Comment by dimaip** [comment]
Oh, I got ya, it's the dependency from the python counterpart...
Thanks for explaining!
Too bad, was such a nice experience integrating your package, but we'd have to use for alternatives :-(

**Comment by sotjdisc** [comment]
Hi,

could you perhaps use the alternative library as suggested in this issue?

https://github.com/seatgeek/fuzzywuzzy/issues/333

**Comment by nol13** [comment]
Hmm, ya looks like maybe I can. The original has updated it's license too it looks like. Will do a double check to make sure I don't have any other gpl code im using and I'll update the license.

**Comment by LucasLongarini** [comment]
Hello 👋 , any update on this? We're facing the same issue where we'd love to use this library but cant because of the license

**Comment by neo-luca** [comment]
Hey @nol13 we are also blocked by the GPL license. Do you have plans on updating the package license?

**Comment by nol13** [comment]
Fuzzball is now licensed under MIT.
