### ISSUE TITLE
FYI - using in BigQuery

### ISSUE THREAD

**Issue by fhoffa** [nol13/fuzzball.js#8]
As a FYI, I'm using fuzzball.js in BigQuery as shared persistent functions:

- https://medium.com/@hoffa/new-in-bigquery-persistent-udfs-c9ea4100fd83

```
SELECT fhoffa.x.levenshtein('felipe', 'hoffa')
 , fhoffa.x.levenshtein('googgle', 'goggles')
 , fhoffa.x.levenshtein('is this the', 'Is This The')

6  2  0

```
Fuzzy choose one:

```
SELECT fhoffa.x.fuzzy_extract_one('jony' 
  , (SELECT ARRAY_AGG(name) 
   FROM `fh-bigquery.popular_names.gender_probabilities`) 
  #, ['john', 'johnny', 'jonathan', 'jonas']
)

johnny
```

**Comment by kxe2732** [comment]
FYI I was not able to get it to work.  
I was getting a "require is not defined at gs://.../js/fuzzball.js line 4"  Seems like I need another library in my environment so I found require.js then added this to the UDF:  OPTIONS (library='gs://.../js/require.js', library = 'gs://.../js/fuzzball.js');

Now I am getting an error at line 5:  Module name "lib/fbdifflib.js" has not been loaded yet for context: _

**Comment by nol13** [comment]
@kxe2732, from the example, does using fuzzball.umd.min.js instead of fuzzball.js work? (umd build is in the /dist folder)

fuzzball.js is for node environments, but look's like this needs the standalone build.

**Comment by kxe2732** [comment]
Thanks @nol13 Worked as expected.  Very helpful.

**Comment by fhoffa** [comment]
My mistake! it's running now.

The library was missing my read permissions 😳

(I updated the ACL on my GCS copy of fuzzball today, when applying new ACLs for a different library)

**Comment by joshirvmck** [comment]
These functions recently started to give the error: "Error getting metadata for external code resource, please verify you have provided a valid path and/or that you have access to the resource: gs://fh-bigquery/js/fuzzball.umd.min.js" 

Was there a change to cause this to happen?
